### ISSUE TITLE
Missing file resnet18_k2.prototxt for PACS dataset with 2 latent domains.

### ISSUE THREAD

**Issue by tarujg** [mancinimassimiliano/latent_domains_DA#2]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by mancinimassimiliano** [comment]
Hi @tarujg and thanks for pointing out this. Actually, there was a mistake in the README: for PACS we used `resnet18_k3.prototxt` with 3 latent domains. This file is already included within the repo in `models/latentDA`.

**Comment by tarujg** [comment]
Hi @mancinimassimiliano 

1. How can I reproduce the results on Office-31 from the paper?
2. How do you generate the resnet18 network for 2 latent domains? 
3. How does the slice point get set for PACS?
